server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      hikari:
        jdbc-url: jdbc:h2:~/test;AUTO_SERVER=true
        driver-class-name: org.h2.Driver
        username: sa
        password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        SQL: DEBUG
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      output:
        ansi:
          enabled: always

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE
